apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::342537627352:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-9QUXHNFUXH0E
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::342537627352:role/UdacityFlaskDeployCBKubectlRole
      username: build    
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-21T19:55:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1641"
  uid: 1bf846d6-22a0-4630-98c0-31b37dc0c803
